x-nginx-template: &nginx-template
  image: nginx
  networks:
    - common
  depends_on:
    - api

services:
  api:
    build: api
    container_name: api
    networks:
      - common

  client:
    build: client
    container_name: client
    networks:
      - common
    depends_on:
      - nginx-no-cache
      - nginx-simple-cache
      - nginx-stale-cache

  nginx-no-cache:
    << : *nginx-template  
    container_name: nginx-no-cache
    volumes:
      - ./nginx/nginx-no-cache.conf:/etc/nginx/nginx.conf

  nginx-simple-cache:
    << : *nginx-template  
    container_name: nginx-simple-cache
    volumes:
      - ./nginx/nginx-simple-cache.conf:/etc/nginx/nginx.conf

  nginx-stale-cache:
    << : *nginx-template  
    container_name: nginx-stale-cache
    volumes:
      - ./nginx/nginx-stale-cache.conf:/etc/nginx/nginx.conf

networks:
  common: