x-nginx-template: &nginx-template
  image: nginx
  networks:
    - common
  depends_on:
    - api

services:
  api:
    build: api
    container_name: api
    networks:
      - common

  client:
    build: client
    container_name: client
    networks:
      - common
    depends_on:
      - nginx-background-update

  nginx-background-update:
    << : *nginx-template  
    container_name: nginx-background-update
    ports:
      - 8005:8000
    volumes:
      - ./nginx/nginx-background-update.conf:/etc/nginx/nginx.conf

networks:
  common: